MyParcelCOM/api-sdk-php

- src/Authentication/ClientCredentials.php
Fixes [API-60](https://myparcelcom.myjetbrains.com/youtrack/issue/API-60)
> Fixing API-60: SDK authorization exception.

- src/Authentication/ClientCredentials.php
- src/MyParcelComApi.php
Tests will be added when implementing https://myparcelcom.myjetbrains.com/youtrack/issue/API-56
> :sparkles: added clear cache methods

- src/MyParcelComApiInterface.php
- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/Shipment.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-v1-shipments-shipment-id-1-statuses.json
- tests/Stubs/get/https---api-v1-statuses-status-id-2.json
- tests/Stubs/get/https---api-v1-statuses-status-id-3.json
- tests/Stubs/get/https---api-v1-statuses-status-id-4.json
- tests/Stubs/get/https---api-v1-statuses-status-id-5.json
- tests/Unit/ShipmentTest.php
> ✨ Added Shipment::getStatusHistory()

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Stubs/get/https---api-v1-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-v1-shipments.json
- tests/Unit/ShipmentTest.php
[API-81 Add tracking code & url to shipments](https://myparcelcom.myjetbrains.com/youtrack/issue/API-81)
> ✨ Added tracking code and url to shipment

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-v1-carriers-4a78637a-5d81-4e71-9b18-c338968f72fa-pickup-dropoff-locations-GB-B48 7QN.json
- tests/Stubs/get/https---api-v1-carriers.json
[part of MP-76](https://myparcelcombv.atlassian.net/browse/MP-76)
> MP-77, MP-78 Retrieving all PUDO points does not fail

- src/Validators/ShipmentValidator.php
- tests/Unit/ShipmentValidatorTest.php
[MP-144](https://myparcelcombv.atlassian.net/browse/MP-144)
> MP-144 Shipment Validator

- src/Resources/Interfaces/ServiceOptionInterface.php
- src/Resources/ServiceOption.php
- tests/Feature/ResourceFactoryTest.php
- tests/Unit/ServiceOptionTest.php
[MP-276](https://myparcelcombv.atlassian.net/browse/MP-276)
Part of: [MP-197](https://myparcelcombv.atlassian.net/browse/MP-197)
> MP-276 Add service-option category and code to sdk

- src/Resources/Interfaces/ServiceInterface.php
- src/Resources/Proxy/ServiceProxy.php
- src/Resources/Service.php
- tests/Feature/Proxy/ServiceProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-v1-services-433285bb-2e34-435c-9109-1120e7c4bce4.json
- tests/Stubs/get/https---api-v1-services-a3057e77-005b-4945-a41c-20ddbe4dab08.json
- tests/Unit/ServiceTest.php
[MP-647](https://myparcelcombv.atlassian.net/browse/MP-647)
Part of: [MP-616](https://myparcelcombv.atlassian.net/browse/MP-616)
> MP-647 Add delivery method to service resource

- README.md
- src/MyParcelComApiInterface.php
- src/Resources/CarrierContract.php
- src/Resources/PickUpDropOffLocation.php
- src/Resources/Service.php
- tests/Stubs/get/https---api-v1-service-contracts--filter-carrier_contract--f1630e62-4645-448d-af22-7d5bac0f502d.json
- tests/Unit/CarrierTest.php
- tests/Unit/FileTest.php
- tests/Unit/PickUpDropOffLocationTest.php
- added `carrier` relationship to PUDO location
- fixed some (unused) callback functions
> ♻️ add carrier relationship to pudo location

- src/MyParcelComApiInterface.php
- src/Resources/Contract.php
- src/Resources/Interfaces/ContractInterface.php
- src/Resources/Interfaces/ResourceInterface.php
- src/Resources/Interfaces/ServiceContractInterface.php
- src/Resources/Proxy/ContractProxy.php
- src/Resources/Proxy/ServiceContractProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceContract.php
- tests/Feature/Proxy/ContractProxyTest.php
- tests/Feature/Proxy/ServiceContractProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-contracts-f1630e62-4645-448d-af22-7d5bac0f502d.json
- tests/Stubs/get/https---api-service-contracts-/filter-contract--f1630e62-4645-448d-af22-7d5bac0f502d.json
- tests/Stubs/get/https---api-service-contracts-f94dda81-c418-4077-ba7c-87ddf9076c28.json
- tests/Stubs/get/https---api-services-372c961e-006d-4351-b4e6-4dc9036e939b-contracts.json
- tests/Stubs/get/https---api-services-433285bb-2e34-435c-9109-1120e7c4bce4-contracts.json
- tests/Stubs/get/https---api-services-605c33ba-5504-4bb0-9467-d8901195923c-contracts.json
- tests/Stubs/get/https---api-services-a3057e77-005b-4945-a41c-20ddbe4dab08-contracts.json
- tests/Unit/ContractTest.php
- tests/Unit/ServiceContractTest.php
**Changes**
- Renamed CarrierContract to Contract
- https://myparcelcombv.atlassian.net/browse/MP-1617 (story)
- https://myparcelcombv.atlassian.net/browse/MP-1719 (subtask)
> MP-1719 Renamed CarrierContract to Contract.

- src/Resources/Interfaces/PickUpDropOffLocationInterface.php
- src/Resources/PickUpDropOffLocation.php
- src/Resources/ResourceFactory.php
- tests/Feature/ResourceFactoryTest.php
- tests/Unit/PickUpDropOffLocationTest.php
- [MP-1669](https://myparcelcombv.atlassian.net/browse/MP-1669)
> MP-1669 Update pudo location resource

- src/Resources/Interfaces/StatusInterface.php
- src/Resources/Proxy/StatusProxy.php
- src/Resources/Status.php
- tests/Feature/Proxy/StatusProxyTest.php
- tests/Unit/StatusTest.php
[MP-1675](https://myparcelcombv.atlassian.net/browse/MP-1675)
> Added resource_type attribute to status resource.

- src/Resources/Interfaces/ShopInterface.php
- src/Resources/Proxy/ShopProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/Shop.php
- tests/Feature/Proxy/ShopProxyTest.php
- tests/Stubs/get/https---api-shops-shop-id-1.json
- tests/Stubs/get/https---api-shops.json
- tests/Stubs/get/https---api-shops/page-number--1/page-size--30.json
- tests/Unit/ShopTest.php
[MP-1674](https://myparcelcombv.atlassian.net/browse/MP-1674)
> Added website attribute to shops resource.

- src/MyParcelComApi.php
- src/Resources/Interfaces/ServiceRateInterface.php
- src/Shipments/PriceCalculator.php
- tests/Unit/PriceCalculatorTest.php
https://myparcelcombv.atlassian.net/browse/MP-1676
> Made sdk calculator be able to ignore null priced services and service options

- src/Resources/CarrierStatus.php
- src/Resources/Error.php
- src/Resources/Interfaces/CarrierStatusInterface.php
- src/Resources/Interfaces/ErrorInterface.php
- src/Resources/Interfaces/ShipmentStatusInterface.php
- src/Resources/Proxy/ServiceOptionProxy.php
- src/Resources/Proxy/ShipmentStatusProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceRate.php
- src/Resources/Shipment.php
- src/Resources/ShipmentStatus.php
- src/Resources/Traits/JsonSerializable.php
- src/Shipments/PriceCalculator.php
- src/Utils/DateUtils.php
- tests/Feature/MyParcelComApiTest.php
- tests/Feature/Proxy/ShipmentStatusProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-shipments-shipment-id-1-statuses-shipment-status-id-1.json
- tests/Stubs/get/https---api-shipments-shipment-id-1-statuses.json
- tests/Traits/MocksApiCommunication.php
- tests/Unit/CarrierStatusTest.php
- tests/Unit/ErrorTest.php
- tests/Unit/ShipmentStatusTest.php
*Jira:* https://myparcelcombv.atlassian.net/browse/MP-1900
> ✨ Updated resources to match new shipment-statuses

- src/MyParcelComApi.php
- src/Validators/ShipmentValidator.php
- tests/Feature/MyParcelComApiTest.php
- tests/Unit/ShipmentValidatorTest.php
**Changes**
- Removed automatic determination of service and contract, based on price
- Removed service and contract from required list in validator class
- Adjusted tests to allow for service and contract to be optional
**Related issues**
- https://myparcelcombv.atlassian.net/browse/MP-1982
> Remove automatic selection of service and contract

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Unit/ShipmentTest.php
- None.
**Changes**
- Removed weight and physical_properties_verified properties from the shipment resource.
> Removed old unused and confusing properties from the Shipment resource.

- src/Resources/Interfaces/ServiceInterface.php
- src/Resources/Proxy/ServiceProxy.php
- src/Resources/Service.php
- tests/Feature/Proxy/ServiceProxyTest.php
- tests/Stubs/get/https---api-services-433285bb-2e34-435c-9109-1120e7c4bce4.json
- tests/Stubs/get/https---api-services-a3057e77-005b-4945-a41c-20ddbe4dab08.json
- tests/Stubs/get/https---api-services/filter-carrier--eef00b32-177e-43d3-9b26-715365e4ce46/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-delivery_method--pick-up/filter-carrier--eef00b32-177e-43d3-9b26-715365e4ce46/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-delivery_method--pick-up/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-region_from--59f129d1-23fa-427e-b0d3-50a498a99044/filter-region_to--59f129d1-23fa-427e-b0d3-50a498a99044.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/page-number--1/page-size--30.json
- tests/Unit/ServiceTest.php
- [Subtask: MP-2480](https://myparcelcombv.atlassian.net/browse/MP-2480)
- [Story: MP-2411](https://myparcelcombv.atlassian.net/browse/MP-2411)
> MP-2480 Added uses_volumetric_weight attribute to service resource.

- src/Resources/ResourceFactory.php
- https://myparcelcombv.atlassian.net/browse/MP-2275
> 🐛 ResourceFactory sets regionFrom and regionTo on services twice.

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/Shipment.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments/filter-shop--shop-id-1/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-shipments/page-number--1/page-size--30.json
- tests/Unit/ShipmentTest.php
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2574)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2306)
> MP-2574 Added total_value to shipment attributes.

- composer.lock
Fixes: https://github.com/MyParcelCOM/api-sdk-php/network/alerts
> ⬆️ Updated packages

- src/Resources/Interfaces/ServiceInterface.php
- src/Resources/Interfaces/ServiceRateInterface.php
- src/Resources/Proxy/ServiceProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/Service.php
- src/Resources/ServiceRate.php
- tests/Feature/Proxy/ServiceProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--500/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--500/filter-volumetric_weight--12800/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/page-number--1/page-size--30.json
- tests/Traits/MocksApiCommunication.php
- tests/Unit/Authentication/ClientCredentialsTest.php
- tests/Unit/PromiseCollectionTest.php
- tests/Unit/ServiceRateTest.php
- tests/Unit/ServiceTest.php
- tests/Unit/UrlBuilderTest.php
Remove deprecated features before release of v2.0.0
> 🔥 step_price step_size region_from region_to

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments/filter-shop--shop-id-1/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-shipments/page-number--1/page-size--30.json
- tests/Unit/ShipmentTest.php
https://myparcelcombv.atlassian.net/browse/MP-3215
> MP-3215 ✨ Add customer_reference to shipment resource

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
Introduced a constant for TTL that represents no cache at all.
> 🐛 Using 0 for  when intending to disable cache 

- src/MyParcelComApiInterface.php
- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Unit/ShipmentTest.php
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3513
- Story: https://myparcelcombv.atlassian.net/browse/MP-3390
> MP-3513 Added tags to the shipment resource.

- src/Resources/Interfaces/ShipmentItemInterface.php
- src/Resources/ShipmentItem.php
- tests/Unit/ShipmentItemTest.php
https://myparcelcombv.atlassian.net/browse/MP-3668
- Added `image_url` to shipment item.
- Changed type hints to include nullable.
> MP-3668 ✨ Added image url to shipment item

- composer.lock
- docker-compose.yml
- docker/php/Dockerfile
- docker/php70/Dockerfile
- docker/php71/Dockerfile
- docker/php72/Dockerfile
- src/Resources/Interfaces/CustomsInterface.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments/filter-shop--shop-id-1/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-shipments/page-number--1/page-size--30.json
- tests/Unit/CustomsTest.php
- tests/Unit/ShipmentTest.php
Our API does not accept `DDU` anymore since 2018-12-09.
> 💥 Changed DDU to DAP

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments/filter-shop--shop-id-1/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-shipments/page-number--1/page-size--30.json
- tests/Unit/ShipmentTest.php
https://myparcelcombv.atlassian.net/browse/MP-3748
> ✨ Added sender_tax_number to shipment resource

- src/Resources/Carrier.php
- src/Resources/Interfaces/FileInterface.php
- src/Resources/Proxy/CarrierProxy.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-carriers-eef00b32-177e-43d3-9b26-715365e4ce46.json
- tests/Stubs/get/https---api-carriers/page-number--1/page-size--30.json
- tests/Unit/ShipmentTest.php
https://myparcelcombv.atlassian.net/browse/MP-2632
- Added `label_mime_types` on Carrier resource.
- Allowed modification of Shipment meta `label_mime_type`.
> MP-2632 ✨ Label mime types for carriers and shipments

- src/Resources/Customs.php
- tests/Unit/CustomsTest.php
- tests/Unit/ShipmentTest.php
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3927
- Story: https://myparcelcombv.atlassian.net/browse/MP-3773
> MP-3927 Added shipping_value to the Customs class.

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- src/Resources/Proxy/FileStreamProxy.php
https://myparcelcombv.atlassian.net/browse/MP-4074
> MP-4074 ♻️ Remove and reduce default caching

- src/Resources/Interfaces/ServiceRateInterface.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceRate.php
- src/Shipments/PriceCalculator.php
- tests/Feature/ResourceFactoryTest.php
- tests/Traits/MocksContract.php
- tests/Unit/PriceCalculatorTest.php
- tests/Unit/ServiceRateTest.php
https://myparcelcombv.atlassian.net/browse/MP-3918
> MP-4111 ✨ Added fuel_surcharge to service-rate resource

- composer.json
- src/Enums/TaxTypeEnum.php
- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- src/Resources/ShipmentItem.php
- src/Resources/TaxIdentificationNumber.php
- tests/Unit/ShipmentItemTest.php
- tests/Unit/ShipmentTest.php
- tests/Unit/TaxIdentificationNumberTest.php
https://myparcelcombv.atlassian.net/browse/MP-4335
> MP-4335 ✨ Shipment tax identification numbers

- src/MyParcelComApi.php
- src/Resources/Address.php
- src/Resources/Interfaces/AddressInterface.php
- tests/Unit/AddressTest.php
https://myparcelcombv.atlassian.net/browse/MP-4453
> MP-4453 ♻️ Add state_code to service regions

- src/Authentication/ClientCredentials.php
https://myparcelcombv.atlassian.net/browse/MP-5001
> MP-5001 🔒️ Store cached auth token per client ID

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- src/Resources/Interfaces/ServiceRateInterface.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceRate.php
- src/Resources/Traits/JsonSerializable.php
- src/Shipments/PriceCalculator.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--500/filter-service--e097a359-5e05-465c-a75f-42ed5ed799e6/filter-organization--org-id/include-contract,service/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-address_from--country_code--GB/filter-address_from--postal_code--1AA BB2/filter-address_to--country_code--CA/filter-address_to--postal_code--W8 6UX.json
- tests/Stubs/patch/https---api-shipments-new-shipment.json
- tests/Stubs/post/https---api-get-dynamic-service-rates.json
- tests/Stubs/post/https---api-shipments.json
- tests/Traits/MocksApiCommunication.php
- tests/Traits/MocksContract.php
- tests/Unit/PriceCalculatorTest.php
- tests/Unit/ServiceRateTest.php
https://myparcelcombv.atlassian.net/browse/MP-5200
---
- Added `is_dynamic` to ServiceRate resource.
- Added `resolveDynamicServiceRates()` function that communicates with our `/get-dynamic-service-rates` RPC endpoint.
- Updated `getServiceRatesForShipment()` and the `PriceCalculator` to recognize dynamic rates and resolve their price.
TODO
- Write tests
> 💸 Dynamic service rates

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- tests/Feature/MyParcelComApiTest.php
- tests/Traits/MocksApiCommunication.php
- Sending the Idempotency-Key header when the $idempotencyKey argument is set on `createShipment` call
> ✨ Introduced idempotency feature for createShipment endpoint

- src/Resources/CarrierStatus.php
- src/Resources/Interfaces/CarrierStatusInterface.php
- tests/Unit/CarrierStatusTest.php
- Added tracking code proprety to CarrierStatus model.
- https://myparcelcombv.atlassian.net/browse/MP-5361
> MP-5361 Tracking code on Carrier statuses

- src/MyParcelComApi.php
- tests/Feature/MyParcelComApi/CollectionsTest.php
- 🐞 `updateCollection` method now filters out properties to patch.
- https://myparcelcombv.atlassian.net/browse/MP-6434
> MP-6434 Update collection errors

- src/MyParcelComApi.php
- src/Resources/Collection.php
- src/Resources/Interfaces/ShipmentSurchargeInterface.php
- src/Resources/Proxy/ShipmentSurchargeProxy.php
- src/Resources/Shipment.php
- src/Resources/ShipmentSurcharge.php
- src/Validators/ShipmentSurchargeValidator.php
- tests/Feature/MyParcelComApi/CarriersTest.php
- tests/Feature/MyParcelComApi/CollectionsTest.php
- tests/Feature/MyParcelComApi/PickUpDropOffLocationsTest.php
- tests/Feature/MyParcelComApi/RegionsTest.php
- tests/Feature/MyParcelComApi/ResourcesTest.php
- tests/Feature/MyParcelComApi/ServiceRatesTest.php
- tests/Feature/MyParcelComApi/ServicesTest.php
- tests/Feature/MyParcelComApi/ShipmentStatusesTest.php
- tests/Feature/MyParcelComApi/ShipmentSurchargesTest.php
- tests/Feature/MyParcelComApi/ShopsTest.php
- tests/Feature/Proxy/BrokerProxyTest.php
- tests/Feature/Proxy/CollectionProxyTest.php
- tests/Feature/Proxy/ManifestProxyTest.php
- tests/Feature/Proxy/OrganizationProxyTest.php
- tests/Stubs/get/https---api-shipment-surcharges-4afa3758-c425-48bc-96ef-ba43c5da4082.json
- tests/Stubs/get/https---api-shipments-shipment-id-1/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges.json
- tests/Stubs/get/https---api-shipments/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges/filter-shop--shop-id-1/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-shipments/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges/page-number--1/page-size--100.json
- tests/Stubs/patch/https---api-shipment-surcharges-4afa3758-c425-48bc-96ef-ba43c5da4082.json
- tests/Stubs/post/https---api-shipment-surcharges.json
https://myparcelcombv.atlassian.net/browse/MP-6874
---
- Added `shipment` relationship to `ShipmentSurcharge` resource
- Added functions to manage shipment-surcharges
- Added tests
> ✨ Shipment surcharge management

- src/MyParcelComApi.php
- src/Resources/Interfaces/PickUpDropOffLocationInterface.php
* Add locationType functions to PickUpDropOffLocationInterface by @LucaScorpion in https://github.com/MyParcelCOM/api-sdk-php/pull/255
> 🚀 Update staging
