- src/Resources/Position.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-v1-carriers-eef00b32-177e-43d3-9b26-715365e4ce46-pickup-dropoff-locations-GB-B48 7QN.json
- tests/Unit/PickUpDropOffLocationTest.php
- tests/Unit/PositionTest.php
The SDK never exposed units to the user as a property of location, but always converted to and from meters.
> MP-170 ♲ Removed unit attribute from pudo locations

- src/Resources/Contract.php
- src/Resources/Interfaces/ContractInterface.php
- src/Resources/Proxy/ContractProxy.php
- tests/Feature/Proxy/ContractProxyTest.php
- tests/Stubs/get/https---api-contracts-f1630e62-4645-448d-af22-7d5bac0f502d.json
- tests/Unit/ContractTest.php
- [MP-1668](https://myparcelcombv.atlassian.net/browse/MP-1668)
**Notes**
- The Jira issue specifies that the owner relationship should also be added. The owner relationship can be of types Broker or Organization however, and both of those are not yet added to the SDK as resource. Therefore, the owner relationship was not not added in this PR.
I think it's also not yet necessary to have the owner relationship on a contract in the SDK.
> MP-1668 Update Contract resource

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-regions/filter-country_code--GB/filter-postal_code--NW1 6XE/page-number--1/page-size--30.json
**Changes**
- Changed `getRegions()` method signature to accept  only a `$filters` array
- Ensured backward compatibility of above changes
- Added test to ensure `postal_code` filter is correctly applied
**Related issues**
- https://myparcelcombv.atlassian.net/browse/MP-2112
> Add postal code filter to get regions

- src/MyParcelComApi.php
- src/Resources/Interfaces/PhysicalPropertiesInterface.php
- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/PhysicalProperties.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- src/Shipments/PriceCalculator.php
- src/Shipments/ServiceMatcher.php
- tests/Feature/MyParcelComApiTest.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-service-rates/filter-weight--500/filter-volumetric_weight--12800/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-address_from--country_code--GB/filter-address_from--country_code--GB.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-address_from--country_code--GB/filter-address_to--country_code--GB.json
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments/filter-shop--shop-id-1/page-number--1/page-size--30.json
- tests/Stubs/get/https---api-shipments/page-number--1/page-size--30.json
- tests/Traits/MocksContract.php
- tests/Unit/PhysicalPropertiesTest.php
- tests/Unit/PriceCalculatorTest.php
- tests/Unit/ServiceMatcherTest.php
- tests/Unit/ServiceTest.php
- tests/Unit/ShipmentTest.php
**Changes**
- Implemented volumetric weight for service rate retrieval and shipment creation flow.
- Fixed a bug where all available service rates for all services were returned when no services could be found for a shipment (it populated the filter[service] with nothing, so instead, the service rates for all services were returned).
- https://myparcelcombv.atlassian.net/browse/MP-2457
> MP-2457 add volumetric weight to sdk

- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Unit/ShipmentTest.php
https://myparcelcombv.atlassian.net/browse/MP-3138
- Added `channel` attribute to shipment resource.
- Added `@deprecated` to shipment weight functions because they were not inherited.
> MP-3138 ✨ Added channel attribute to shipment resource

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
TTL of cache can be passed to `getResourceById` which enables customization of the `getShipment` method too. With this PR the `getShipment` method will no longer automatically cache the retrieved shipment resource.
In addition, I added `$ttl` as a parameter (with default value set) on all get methods for all types of resources. This makes cache TTL configurable for all
> ✨ Cache TTL can be changed when getting a shipment

- composer.json
The symfony/cache version wouldn't work in conjunction with packages that require newer version. That's I suggest to allow the 4.* family as well.
> 🔼 Allowing symafony/cache version 4.0 and newer to be used as well

- composer.json
- docker/php/Dockerfile
- docker/php70/Dockerfile
- docker/php71/Dockerfile
- docker/php72/Dockerfile
- Added `symfony/cache ^5.0` to support Laravel 7 projects.
> Support newer symfony cache

- .circleci/config.yml
- composer.lock
- src/Authentication/ClientCredentials.php
- src/MyParcelComApi.php
- tests/Feature/Proxy/CarrierProxyTest.php
- tests/Feature/Proxy/ContractProxyTest.php
- tests/Feature/Proxy/FileProxyTest.php
- tests/Feature/Proxy/FileStreamProxyTest.php
- tests/Feature/Proxy/RegionProxyTest.php
- tests/Feature/Proxy/ServiceOptionProxyTest.php
- tests/Feature/Proxy/ServiceProxyTest.php
- tests/Feature/Proxy/ShipmentProxyTest.php
- tests/Feature/Proxy/ShipmentStatusProxyTest.php
- tests/Feature/Proxy/ShopProxyTest.php
- tests/Feature/Proxy/StatusProxyTest.php
- tests/Traits/MocksApiCommunication.php
Symfony 5.0.0 removed their PSR-16 cache classes.
A solution is to wrap their PSR-6 cache classes into their `Psr16Cache` wrapper.
CircleCI is updated to test this breaking change in Symfony during the PHP 7.2 test flow.
> MP-3659 🐛 Symfony cache fallback

- src/MyParcelComApi.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
`meta` was implemented but it was sent as a child of `data`
> 🐛 Shipment meta should be outside of data

- src/MyParcelComApi.php
If you are using `getServiceRatesForShipment()` you would expect the internal `getServices()` to use the same `$ttl`.
> ♿️ Pass TTL down to getServices() function

- src/Collection/ArrayCollection.php
- src/Collection/CollectionInterface.php
- src/Collection/RequestCollection.php
- tests/Unit/PromiseCollectionTest.php
Since our API endpoints are able to return 100 results, our SDK should be able to `->limit(100)` as well.
> ♻️ Increase max resource limit from 30 to 100

- src/Resources/Proxy/ServiceProxy.php
- src/Resources/Service.php
- tests/Feature/ResourceFactoryTest.php
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--500/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/filter-organization--org-id/include-contract,service/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--500/filter-volumetric_weight--12800/filter-service--a3057e77-005b-4945-a41c-20ddbe4dab08/include-contract,service/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-services-433285bb-2e34-435c-9109-1120e7c4bce4.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-address_from--country_code--GB/filter-address_from--postal_code--1AA BB2/filter-address_to--country_code--GB/filter-address_to--postal_code--B48 7QN.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-address_from--country_code--GB/filter-address_from--postal_code--1AA BB2/filter-address_to--country_code--GB/filter-address_to--postal_code--W8 6UX.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-carrier--eef00b32-177e-43d3-9b26-715365e4ce46/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-delivery_method--pick-up/filter-carrier--eef00b32-177e-43d3-9b26-715365e4ce46/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/filter-delivery_method--pick-up/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-services/filter-has_active_contract--true/page-number--1/page-size--100.json
- tests/Unit/ServiceTest.php
A client reported it does not see the difference between multiple returned services.
The difference is in the regions_from and regions_to, but these values are not set / present in the output.
> ♻️ json_encode service region arrays

- src/Resources/Traits/JsonSerializable.php
This PR implements the `is_object()` suggestion from https://github.com/MyParcelCOM/api-sdk-php/pull/170 including a check for a class path.
This check is added because the signature of `method_exists()` allows for objects or class paths:
```php
method_exists(object|string $object_or_class, string $method): bool
```
> 🧑‍💻 Check if value is an object or class before calling method_exists()

- src/MyParcelComApi.php
- src/Resources/Interfaces/ServiceRateInterface.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceRate.php
- src/Shipments/PriceCalculator.php
- tests/Feature/MyParcelComApiTest.php
- tests/Stubs/get/https---api-service-rates/filter-has_active_contract--true/filter-weight--9000/filter-service--e097a359-5e05-465c-a75f-42ed5ed799e6/filter-organization--org-id/include-contract,service/page-number--1/page-size--100.json
- tests/Traits/MocksContract.php
- tests/Unit/ServiceRateTest.php
https://myparcelcombv.atlassian.net/browse/MP-5700
---
- Add `weight_bracket` and `bracket_price` to the `ServiceRate` model.
- Use the bracket price in the `getServiceRatesForShipment()` function.
- Use the weight bracket in the `PriceCalculator` class.
> ⚖️ Support weight brackets on ServiceRates

- .github/workflows/ci.yml
- README.md
- phpunit.xml
We no longer use CircleCI to run the tests, so the badge needs to point to GitHub Actions:
[![GitHub Actions](https://github.com/myparcelcom/api-sdk-php/actions/workflows/ci.yml/badge.svg)](https://github.com/myparcelcom/api-sdk-php/actions)
> 👷 Fix CI badge

- src/MyParcelComApi.php
Patching a collection should be done via `updateCollection()` since not all properties should be sent to the API.
> 👌🏻 Use updateCollection() to register the collection

- src/Resources/ShipmentItem.php
- tests/Unit/ShipmentItemTest.php
The `ceil()` function should not be called when setting the shipment item weight to `null`.
> 🐛 Fix `TypeError` when setting item weight to `null`

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- src/Resources/Interfaces/ShipmentSurchargeInterface.php
- src/Resources/Proxy/ShipmentSurchargeProxy.php
- src/Resources/ShipmentSurcharge.php
- tests/Feature/MyParcelComApi/ShipmentSurchargesTest.php
- tests/Stubs/get/https---api-shipment-surcharges/page-number--1/page-size--100.json
The `shipment` relationship cannot be patched (API returns error) so it should be removed from the request body.
I also added a helper method to get all shipment surcharges.
> 🐛 Fix patching a shipment-surcharge

- docker/php8/Dockerfile
- src/Resources/Interfaces/ServiceOptionInterface.php
- src/Resources/Proxy/ServiceOptionProxy.php
- src/Resources/ResourceFactory.php
- src/Resources/ServiceOption.php
- src/Resources/Traits/JsonSerializable.php
- src/Resources/Traits/ProcessIncludes.php
- src/Resources/Traits/ProxiesResource.php
- tests/Feature/Proxy/ServiceOptionProxyTest.php
- tests/Stubs/get/https---api-service-options-d4637e6a-4b7a-44c8-8b4d-8311d0cf1238.json
- tests/Stubs/get/https---api-shipments-shipment-id-1.json
- tests/Stubs/get/https---api-shipments-shipment-id-1/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges.json
- tests/Stubs/get/https---api-shipments/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges/filter-shop--shop-id-1/page-number--1/page-size--100.json
- tests/Stubs/get/https---api-shipments/include-shop,shipment_status,contract,service,service_options,files,shipment_surcharges/page-number--1/page-size--100.json
- tests/Unit/Resources/ServiceOptionTest.php
- `ServiceOption` models can have values when added to a `Shipment` (used when posting new shipments).
- `ServiceOptionProxy` models can have values when populated on a `Shipment` (used when getting shipments).
- When the `ResourceFactory` is populating included resources, it needs to respect existing `Proxy` relationships.
- Added tests.
> ✨ Allow ServiceOptions to have values

- src/MyParcelComApi.php
- src/Resources/File.php
- src/Resources/Interfaces/FileInterface.php
- src/Resources/Interfaces/ShipmentInterface.php
- src/Resources/Proxy/FileProxy.php
- src/Resources/Proxy/ShipmentProxy.php
- src/Resources/Shipment.php
- src/Resources/Traits/ProxiesResource.php
- tests/Feature/MyParcelComApi/ShipmentsTest.php
- tests/Stubs/post/https---api-multi-colli-shipments/include-colli,colli.files.json
https://myparcelcombv.atlassian.net/browse/MP-7043
---
- Expose the `collo_number` attribute and the `colli` relationship on the `Shipment` model.
- Introduce the `createAndRegisterMultiColliShipment()` function which maps base64 file meta from the response.
- Make the multi-colli master shipment return files from its colli when using `getFiles()`.
- Added tests.
> 🗂️ Support for multi-colli shipments

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- src/Resources/PickUpDropOffLocation.php
- tests/Feature/MyParcelComApi/PickUpDropOffLocationsTest.php
- tests/Stubs/get/https---api-carriers-eef00b32-177e-43d3-9b26-715365e4ce46-pickup-dropoff-locations-GB-B48 7QN/filter-location_type--0--office.json
- tests/Unit/Resources/PickUpDropOffLocationTest.php
✨  Support location_type of PUDO
✨  Support PUDO filters
> ✨ PUDO location_type and filters

- src/MyParcelComApi.php
- src/MyParcelComApiInterface.php
- tests/Feature/MyParcelComApi/DeliveryDatesTest.php
I'm not sure if this is all. I'm not familiar enough with this project, I also didn't test it myself :see_no_evil:
> [sdk] Added carrier code as a required field to the delivery dates endpoint
